version: "3"

services:

  kafka1:
    image: bashj79/kafka-kraft
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9192,CONTROLLER://:9093,LISTENER_DOCKER_EXTERNAL://:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,LISTENER_DOCKER_EXTERNAL://9092:9092
      KAFKA_LOG_DIRS: '/data/kafka'

  kafka2:
    image: bashj79/kafka-kraft
    restart: always
    ports:
      - "9292:9092"
    environment:
      KAFKA_NODE_ID: '2'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9192,CONTROLLER://:9093,LISTENER_DOCKER_EXTERNAL://:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9192,LISTENER_DOCKER_EXTERNAL://9292:9092
      KAFKA_LOG_DIRS: '/data/kafka'

  kafka2:
    image: bashj79/kafka-kraft
    restart: always
    ports:
      - "9392:9092"
    environment:
      KAFKA_NODE_ID: '3'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9192,CONTROLLER://:9093,LISTENER_DOCKER_EXTERNAL://:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9292,LISTENER_DOCKER_EXTERNAL://9392:9092
      KAFKA_LOG_DIRS: '/data/kafka'